### ISSUE TITLE
Loglevel from config/env var is case sensitive

### ISSUE THREAD

**Issue by xoxys** [xoxys/ansible-doctor#2]
Add better parsing for log level passed from config (and catch exception)

```Python
Traceback (most recent call last):
  File "/usr/local/bin/ansible-doctor", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ansibledoctor/__main__.py", line 8, in main
    AnsibleDoctor()
  File "/usr/local/lib/python3.7/site-packages/ansibledoctor/Cli.py", line 23, in __init__
    self.config = self._get_config()
  File "/usr/local/lib/python3.7/site-packages/ansibledoctor/Cli.py", line 60, in _get_config
    self.log.set_level(config.config["logging"]["level"])
  File "/usr/local/lib/python3.7/site-packages/ansibledoctor/Utils.py", line 150, in set_level
    self.logger.setLevel(s)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1353, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 192, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'info'
```

**Comment by xoxys** [comment]
Fixed by https://github.com/xoxys/ansible-doctor/commit/8664a4847771b27d7d6948b11ddc86d35ce92abb
